config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  root "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  resources :company
  resources :jobs, only: [:index, :show, :new, :edit, :create, :destroy] do
    get "jobs/:id", action: :index, on: :collection
    resources :job_applications, only: [:index, :show, :new, :edit, :create]
  end
  resources :job_applications, only: [:destroy, :update]

  resources :myjobs, only: [:index]
  resources :myapplications, only: [:index]
  resources :conversations, only: [:index, :create, :show] do
    post 'create_message', on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :user_id, :post_id, presence: true

  belongs_to :user

  belongs_to :post

  has_many :likes, as: :likeable, dependent: :destroy

  def num_likes
      self.likes.length
  end

end

app/models/company.rb
class Company < ApplicationRecord
  # belongs_to :user
  self.table_name = "companies"

  has_many :jobs, dependent: :destroy
  has_many :job_applications, through: :jobs
  paginates_per 12

  def job_count
    Job.where(company_id: self.id).count
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  has_many :messages, dependent: :destroy
  
end

app/models/experience.rb
class Experience < ApplicationRecord

  validates :user_id, :title, :company, :social_links,:description, presence: true

  belongs_to :user

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  # belongs_to :user
  has_many :job_applications, dependent: :destroy
  # validates :title, :company, :twitter_link, :discord_invite, :description, :chain, presence: true
  paginates_per 5
  belongs_to :company, class_name: 'Company'
  # validates :chain, inclusion: { in: ['Ethereum', 'Polygon', 'Solana', 'Binance Smart Chain', 'Avalanche', 'Fantom', 'Harmony', 'Kusama', 'Polkadot', 'Celo', 'Near', 'Tezos', 'Klaytn', 'Tron', 'Waves', 'EOS', 'Algorand', 'Stellar', 'Cardano', 'Other'] }

  # CHAIN = ['Ethereum', 'Polygon', 'Solana', 'Binance Smart Chain', 'Avalanche', 'Fantom', 'Harmony', 'Kusama', 'Polkadot', 'Celo', 'Near', 'Tezos', 'Klaytn', 'Tron', 'Waves', 'EOS', 'Algorand', 'Stellar', 'Cardano', 'Other']

  def num_applications
    self.job_applications.length
  end


end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  has_many :experiences, through: :user
  has_many :skills, through: :user
  has_noticed_notifications
  after_update_commit { broadcast_notifications }

  private

  def broadcast_notifications
    return if user == job.user
      JobApplicationNotification.with(message: self).deliver_later(user)
    broadcast_prepend_to "notifications_#{job.user.id}",
                          target: "notifications_#{job.user.id}",
                          partial: "notifications/notification",
                          locals: {user:, unread: true }
  end

  def job_owner?
    user == job.user
  end
  # validate :job_owner_cannot_apply

  STATUS = %w(pending accepted rejected)
  def job_owner_cannot_apply
    if job.user_id == user_id
      errors.add(:user_id, "can't be the same as job owner")
    end
  end

  def self.statuses
    %w(pending accepted rejected)
  end

  def self.statuses_for_select
    statuses.map { |status| [status.capitalize, status] }
  end
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :sender, class_name: 'User', foreign_key: 'user_id'
  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

  scope :unread, -> { where(read_at: nil).where(recipient_id: current_user.id) }
end

app/models/post.rb
class Post < ApplicationRecord
  validate :ensure_content

  validates :body, :user_id, presence: true

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :likes, as: :likeable

  # has_one_attached :media, dependent: :destroy

  def ensure_content
    unless self.body.length > 0 || self.media.attached?
      errors.add(:post, 'must have content')
    end
  end

  def num_likes
    self.likes.length
  end

  def who_liked
    self.likes.map { |like| like.user }
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :experiences
  has_many :job_applications
  has_many :jobs
  has_many :skills
  accepts_nested_attributes_for :experiences, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_one_attached :profile_picture
  # has_one_attached :cover_picture
  has_many :notifications, as: :recipient, dependent: :destroy
  has_many :conversations, through: :messages
  has_many :sent_conversations, foreign_key: 'sender_id', class_name: 'Conversation', dependent: :destroy
  has_many :received_conversations, foreign_key: 'recipient_id', class_name: 'Conversation', dependent: :destroy


  JOBS = ["Full Stack Developer", "Front End Developer", "Back End Developer", "DevOps", "Data Scientist", "Data Analyst", "UX Designer", "UI Designer", "Product Manager", "Project Manager", "QA Engineer", "Software Engineer", "Software Architect", "Software Developer", "Software Tester", "Technical Lead", "Technical Architect", "Technical Manager", "Technical Consultant", "Technical Specialist", "Technical Writer", "Technical Recruiter", "Technical Support", "Technical Trainer", "Technical Sales", "Technical Account Manager", "Technical Account Executive", "Technical Account Director", "Technical Account Specialist", "Technical Account Representative", "Technical Account Coordinator", "Technical Account Engineer", "Technical Account Administrator", "Technical Account Associate", "Technical Account Analyst", "Technical Account Advisor", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator"]

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.includes(:comments, :likes, :user).all
    @jobs = Job.all
  end
end

app/controllers/myjobs_controller.rb
class MyjobsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  before_action :skip_authorization, only: [:index]
  def index
    @myjobs = policy_scope(Job).where(user_id: current_user.id).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/myjobs/index.html.erb
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-none">
      <div class="overflow-hidden bg-gray-800 sm:rounded-lg sm:shadow">
        <div class="border-b border-gray-200 bg-gray-800 px-4 py-5 sm:px-6">
          <div class="-ml-4 -mt-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
            <div class="ml-4 mt-4">
              <h3 class="text-lg font-medium leading-6 text-white">Job Postings</h3>
              <p class="mt-1 text-sm text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur.</p>
            </div>
            <div class="ml-4 mt-4 flex-shrink-0">
              <%= link_to "My jobs", myjobs_path, class: "relative inline-flex items-center rounded-md border border-transparent bg-primary-light px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-primary focus:outline-none focus:ring-2 focus:ring-primary-light focus:ring-offset-2" %>

              <%= link_to "Post a job", new_job_path, class: "relative inline-flex items-center rounded-md border border-transparent bg-primary-light px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-primary focus:outline-none focus:ring-2 focus:ring-primary-light focus:ring-offset-2" %>
            </div>
          </div>
        </div>
        <ul role="list" class="divide-y divide-gray-200">
          <% @myjobs.each do |job| %>
            <%= link_to job_path(job) do %>
              <li>
                <div class="px-4 py-4 sm:px-6 hover:bg-gray-900 border-b transation duration-300">
                  <div class="flex items-center justify-between">
                    <div class="truncate text-sm font-medium text-white"><%= job.company %></div>
                    <div class="ml-2 flex flex-shrink-0">
                      <span class="inline-flex rounded-full bg-secondary px-2 text-xs font-semibold leading-5 text-gray-700 align-items-center"><%= job.chain %></span>
                    </div>
                  </div>
                  <div class="mt-2 flex justify-between">
                      <div class="flex items-center text-sm text-gray-500">
                        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" x-description="Heroicon name: mini/users" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                          <path d="M7 8a3 3 0 100-6 3 3 0 000 6zM14.5 9a2.5 2.5 0 100-5 2.5 2.5 0 000 5zM1.615 16.428a1.224 1.224 0 01-.569-1.175 6.002 6.002 0 0111.908 0c.058.467-.172.92-.57 1.174A9.953 9.953 0 017 18a9.953 9.953 0 01-5.385-1.572zM14.5 16h-.106c.07-.297.088-.611.048-.933a7.47 7.47 0 00-1.588-3.755 4.502 4.502 0 015.874 2.636.818.818 0 01-.36.98A7.465 7.465 0 0114.5 16z"></path>
                        </svg>
                        <%= job.title %>
                    </div>

                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>