config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  root "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  resources :company
  resources :jobs, only: [:index, :show, :new, :edit, :create, :destroy] do
    get "jobs/:id", action: :index, on: :collection
    resources :job_applications, only: [:index, :show, :new, :edit, :create]
  end
  resources :job_applications, only: [:destroy, :update]

  resources :myjobs, only: [:index]
  resources :myapplications, only: [:index]
  resources :conversations, only: [:index, :create, :show] do
    post 'create_message', on: :member
  end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  has_many :messages, dependent: :destroy
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @c = current_user.sent_conversations + current_user.received_conversations
    @conversations = policy_scope(Conversation).where(id: @c).order(updated_at: :desc)
  end

  def create
    recipient = User.friendly.find(params[:conversation][:recipient_id])
    conversation = Conversation.new
    conversation.sender = current_user
    conversation.recipient = recipient
    authorize conversation
    # if it exists, find it, otherwise create it
    existing_conversation = Conversation.where(sender: current_user, recipient: recipient) + Conversation.where(sender: recipient, recipient: current_user)
    if existing_conversation.present?
      redirect_to conversations_path, notice: "You already have a conversation with #{recipient.username}"
      return
    end

    if conversation.save
      redirect_to conversations_path, notice: "Conversation started with #{recipient.username}"
    else
      redirect_to user_path(recipient)
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    @message = Message.new
    authorize @conversation

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create_message
    @conversation = Conversation.find(params[:id])
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    authorize @conversation, :create_message?

    if @message.save
      PrivateConversationChannel.broadcast_to(
        @conversation,
        render_to_string(partial: 'messages/message', locals: { message: @message })
      )
      head :ok
    else
      render :show
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end


end

app/views/conversations/_messages.html.erb
<div id="messages">
  <% @conversation.messages.each do |message| %>
    <p><strong><%= message.sender.name %>:</strong> <%= message.content %></p>
  <% end %>
</div>

app/views/conversations/index.html.erb
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-none">
    <div class="overflow-hidden bg-gray-800 sm:rounded-lg sm:shadow">
      <div class="border-b border-gray-700 bg-gray-800 px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-white">My Conversations</h3>
              <p class="mt-1 text-sm text-gray-500">Please do not share any of your personal informations.</p>

      </div>
      <ul role="list" class="divide-y divide-gray-700">
          <% @conversations.each do |conversation| %>
          <li>
            <%= link_to conversation_path(conversation) do %>
              <div class="px-4 py-4 sm:px-6 hover:bg-gray-700 transation duration-300">
                <div class="flex items-center justify-between">
                  <div class="flex items-center justify-between">
                  <% if conversation.sender == current_user %>
                    <% if conversation.recipient.profile_picture.key.present? %>
                      <%= cl_image_tag conversation.recipient.profile_picture.key, height: 250,width:250, crop: :fill, class:"w-10 mr-5 rounded-full" %>
                    <% else %>
                      <img src="https://res.cloudinary.com/dhufhm6ar/image/upload/v1687785983/Windows_10_Default_Profile_Picture.svg_uajtrb.png" class="mr-5 h-10 w-10 border-4 border-white rounded-full">
                    <% end %>
                    <div>
                      <div class="truncate text font-medium text-white"><%= conversation.recipient.username %></div>
                    </div>
                  <% else %>
                    <% if conversation.sender.profile_picture.key.present? %>
                      <%= cl_image_tag conversation.sender.profile_picture.key, height: 250,width:250, crop: :fill, class:"w-10 mr-5 rounded-full" %>
                    <% else %>
                      <img src="https://res.cloudinary.com/dhufhm6ar/image/upload/v1687785983/Windows_10_Default_Profile_Picture.svg_uajtrb.png" class="mr-5 h-10 w-10 border-4 border-white rounded-full">
                    <% end %>
                    <div>
                      <div class="truncate text font-medium text-white"><%= conversation.sender.username %></div>
                    </div>
                  <% end %>
                  </div>
                  <small class="text-white"><%= time_ago_in_words(conversation.created_at) %></small>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div>
  <h1>Conversation between <%= @conversation.sender.username %> and <%= @conversation.recipient.username %></h1>
</div>
<hr>
<!-- component -->
<div class="container mx-auto" data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @conversation.id %>">
  <div class="flex flex-col flex-grow bg-gray-800 shadow-xl rounded-lg h-screen">
    <div class="flex flex-col flex-grow h-0 p-4 overflow-auto">
      <% @conversation.messages.last(20).each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
      <div class="messages" data-chatroom-subscription-target="messages">
      </div>
      <div class="bg-gray-200 p-4">
        <%= simple_form_for :message, url: create_message_conversation_path(@conversation), html: {data: {action: "turbo:submit-end->chatroom-subscription#resetForm"}, class: "d-flex"} do |f|
  %>
        <%= f.input :content,
      label: false,
      placeholder: "Message #{current_user == @conversation.sender ?
        @conversation.recipient.username : @conversation.sender.username}",
      wrapper_html: {class: "flex items-center h-10 w-full rounded px-3 text-sm w-100"},
      required: true
    %>
        <%= f.submit "Send", class: "btn btn-primary mb-3" %>
      <% end %>
    </div>
  </div>
</div>
</div>