config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  root "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  resources :company
  resources :jobs, only: [:index, :show, :new, :edit, :create, :destroy] do
    get "jobs/:id", action: :index, on: :collection
    resources :job_applications, only: [:index, :show, :new, :edit, :create]
  end
  resources :job_applications, only: [:destroy, :update]

  resources :myjobs, only: [:index]
  resources :myapplications, only: [:index]
  resources :conversations, only: [:index, :create, :show] do
    post 'create_message', on: :member
  end

end

app/controllers/myapplications_controller.rb
class MyapplicationsController < ApplicationController

  before_action :authenticate_user!, only: [:index]

  def index
    @applications = policy_scope(JobApplication).where(user: current_user).order(created_at: :desc)
    authorize :MyApplications, :index?

  end
end

app/views/myapplications/index.html.erb
<div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-none">
    <div class="overflow-hidden bg-gray-800 sm:rounded-lg sm:shadow">
      <div class="border-b border-gray-700 bg-gray-800 px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-white">My Applications</h3>
      </div>
      <ul role="list" class="divide-y divide-gray-700">
        <% @applications.each do |app| %>
          <li>
            <%= link_to job_path(app.job) do %>
              <div class="px-4 py-4 sm:px-6 hover:bg-gray-700 transation duration-300">
                <div class="flex items-center justify-between">
                  <div class="flex items-center justify-between">
                    <% if app.user.profile_picture.key.present? %>
                      <%= cl_image_tag app.user.profile_picture.key, height: 250,width:250, crop: :fill, class:"w-10 mr-5 rounded-full" %>
                    <% else %>
                      <img src="https://res.cloudinary.com/dhufhm6ar/image/upload/v1687785983/Windows_10_Default_Profile_Picture.svg_uajtrb.png" class="h-10 w-10 border-4 border-white rounded-full">
                    <% end %>
                    <div>
                      <div class="truncate text font-medium text-white"><%= app.user.username %></div>
                      <small class=" text-white truncate"><%= app.job.title %></small>
                    </div>
                  </div>
                  <small class="text-white text-center">
                      <% if policy(app).destroy? %>
                      <%= link_to job_job_application_path(app.job, app), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <span class="py-3 px-3 rounded bg-red-500"> Delete</span>
                      <% end %>
                    <% end %>
                    <% if app.status == "pending" %>
                      <span class="py-3 px-3 rounded bg-yellow-500"><%= app.status.capitalize %> </span>
                    <% elsif app.status == "accepted" %>
                      <span class="py-3 px-3 rounded bg-green-500"><%= app.status.capitalize %> </span>
                    <% else %>
                      <span class="py-3 px-3 rounded bg-red-500"><%= app.status.capitalize %> </span>
                    <% end %>

                  </small>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>