config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  root "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  resources :company
  resources :jobs, only: [:index, :show, :new, :edit, :create, :destroy] do
    get "jobs/:id", action: :index, on: :collection
    resources :job_applications, only: [:index, :show, :new, :edit, :create]
  end
  resources :job_applications, only: [:destroy, :update]

  resources :myjobs, only: [:index]
  resources :myapplications, only: [:index]
  resources :conversations, only: [:index, :create, :show] do
    post 'create_message', on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :user_id, :post_id, presence: true

  belongs_to :user

  belongs_to :post

  has_many :likes, as: :likeable, dependent: :destroy

  def num_likes
      self.likes.length
  end

end

app/models/company.rb
class Company < ApplicationRecord
  # belongs_to :user
  self.table_name = "companies"

  has_many :jobs, dependent: :destroy
  has_many :job_applications, through: :jobs
  paginates_per 12

  def job_count
    Job.where(company_id: self.id).count
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  has_many :messages, dependent: :destroy
  
end

app/models/experience.rb
class Experience < ApplicationRecord

  validates :user_id, :title, :company, :social_links,:description, presence: true

  belongs_to :user

end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  # belongs_to :user
  has_many :job_applications, dependent: :destroy
  # validates :title, :company, :twitter_link, :discord_invite, :description, :chain, presence: true
  paginates_per 5
  belongs_to :company, class_name: 'Company'
  # validates :chain, inclusion: { in: ['Ethereum', 'Polygon', 'Solana', 'Binance Smart Chain', 'Avalanche', 'Fantom', 'Harmony', 'Kusama', 'Polkadot', 'Celo', 'Near', 'Tezos', 'Klaytn', 'Tron', 'Waves', 'EOS', 'Algorand', 'Stellar', 'Cardano', 'Other'] }

  # CHAIN = ['Ethereum', 'Polygon', 'Solana', 'Binance Smart Chain', 'Avalanche', 'Fantom', 'Harmony', 'Kusama', 'Polkadot', 'Celo', 'Near', 'Tezos', 'Klaytn', 'Tron', 'Waves', 'EOS', 'Algorand', 'Stellar', 'Cardano', 'Other']

  def num_applications
    self.job_applications.length
  end


end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  has_many :experiences, through: :user
  has_many :skills, through: :user
  has_noticed_notifications
  after_update_commit { broadcast_notifications }

  private

  def broadcast_notifications
    return if user == job.user
      JobApplicationNotification.with(message: self).deliver_later(user)
    broadcast_prepend_to "notifications_#{job.user.id}",
                          target: "notifications_#{job.user.id}",
                          partial: "notifications/notification",
                          locals: {user:, unread: true }
  end

  def job_owner?
    user == job.user
  end
  # validate :job_owner_cannot_apply

  STATUS = %w(pending accepted rejected)
  def job_owner_cannot_apply
    if job.user_id == user_id
      errors.add(:user_id, "can't be the same as job owner")
    end
  end

  def self.statuses
    %w(pending accepted rejected)
  end

  def self.statuses_for_select
    statuses.map { |status| [status.capitalize, status] }
  end
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type] }
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  belongs_to :sender, class_name: 'User', foreign_key: 'user_id'
  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true

  scope :unread, -> { where(read_at: nil).where(recipient_id: current_user.id) }
end

app/models/post.rb
class Post < ApplicationRecord
  validate :ensure_content

  validates :body, :user_id, presence: true

  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :likes, as: :likeable

  # has_one_attached :media, dependent: :destroy

  def ensure_content
    unless self.body.length > 0 || self.media.attached?
      errors.add(:post, 'must have content')
    end
  end

  def num_likes
    self.likes.length
  end

  def who_liked
    self.likes.map { |like| like.user }
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :experiences
  has_many :job_applications
  has_many :jobs
  has_many :skills
  accepts_nested_attributes_for :experiences, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_one_attached :profile_picture
  # has_one_attached :cover_picture
  has_many :notifications, as: :recipient, dependent: :destroy
  has_many :conversations, through: :messages
  has_many :sent_conversations, foreign_key: 'sender_id', class_name: 'Conversation', dependent: :destroy
  has_many :received_conversations, foreign_key: 'recipient_id', class_name: 'Conversation', dependent: :destroy


  JOBS = ["Full Stack Developer", "Front End Developer", "Back End Developer", "DevOps", "Data Scientist", "Data Analyst", "UX Designer", "UI Designer", "Product Manager", "Project Manager", "QA Engineer", "Software Engineer", "Software Architect", "Software Developer", "Software Tester", "Technical Lead", "Technical Architect", "Technical Manager", "Technical Consultant", "Technical Specialist", "Technical Writer", "Technical Recruiter", "Technical Support", "Technical Trainer", "Technical Sales", "Technical Account Manager", "Technical Account Executive", "Technical Account Director", "Technical Account Specialist", "Technical Account Representative", "Technical Account Coordinator", "Technical Account Engineer", "Technical Account Administrator", "Technical Account Associate", "Technical Account Analyst", "Technical Account Advisor", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator", "Technical Account Agent", "Technical Account Assistant", "Technical Account Administrator"]

end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.includes(:comments, :likes, :user).all
    @jobs = Job.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
<div
  data-controller="notification"
  data-notification-delay-value="2000"
  class="transition transform duration-1000 hidden z-50"
  data-transition-enter-from="opacity-0 translate-x-6"
  data-transition-enter-to="opacity-100 translate-x-0"
  data-transition-leave-from="opacity-100 translate-x-0"
  data-transition-leave-to="opacity-0 translate-x-6"
>
<div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6 z-50">
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
    <!--
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="p-4">
        <div class="flex items-start">
          <div class="flex-shrink-0">
            <!-- Heroicon name: outline/check-circle -->
            <svg class="h-6 w-6 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm font-medium text-gray-900">Successfully saved!</p>
            <p class="mt-1 text-sm text-gray-500"><%= notice %></p>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <button  data-action="notification#hide" type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-light focus:ring-offset-2">
              <span class="sr-only">Close</span>
              <!-- Heroicon name: mini/x-mark -->
              <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
<% end %>

<% if alert %>
<div
  data-controller="notification"
  data-notification-delay-value="2000"
  class="transition transform duration-1000 hidden z-50"
  data-transition-enter-from="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
  data-transition-enter-to="translate-y-0 opacity-100 sm:translate-x-0"
  data-transition-leave-from="opacity-100"
  data-transition-leave-to="opacity-0"
>
<div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6 z-50">
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
    <!--
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="p-4">
        <div class="flex items-start">
          <div class="flex-shrink-0">
            <!-- Heroicon name: outline/check-circle -->
            <svg class="h-6 w-6 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm font-medium text-gray-900">Error</p>
            <p class="mt-1 text-sm text-gray-500"><%= alert %></p>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <button  data-action="notification#hide" type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-light focus:ring-offset-2">
              <span class="sr-only">Close</span>
              <!-- Heroicon name: mini/x-mark -->
              <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Start Navbar -->
<nav id="topnav" class="defaultscroll is-sticky">
  <div class="container-fluid md:px-8 px-3">
    <!-- Logo container-->
    <%= link_to root_path, class:"logo" do %>
      <div class="block sm:hidden">
        <%= image_tag("logo-icon-40.png", class:"h-10 inline-block dark:hidden") %>
        <%= image_tag("logo-icon-40-white.png", class:"h-10 hidden dark:inline-block") %>
      </div>
      <div class="sm:block hidden">
        <%= image_tag("logo-dark.png", class:"h-[24px] inline-block dark:hidden") %>
        <%= image_tag("logo-white.png", class:"h-[24px] hidden dark:inline-block") %>
      </div>
    <% end %>
    <!-- End Logo container-->
    <!-- Start Mobile Toggle -->
    <div class="menu-extras">
      <div class="menu-item">
        <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
          <div class="lines">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </a>
      </div>
    </div>
    <!-- End Mobile Toggle -->
    <!--Login button Start-->
    <ul class="buy-button list-none mb-0">
      <li class="inline-block mb-0">
        <div class="relative top-[3px]">
          <i class="uil uil-search text-lg absolute top-[3px] end-3"></i>
          <input type="text" class="form-input h-9 pe-10 rounded-3xl sm:w-44 w-36 border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-900" name="s" id="searchItem" placeholder="Search...">
        </div>
      </li>
      <% if !current_user %>
      <li class="inline-block ps-1 mb-0">
          <a href="<%= new_user_session_path %>" class="btn btn-icon rounded-full bg-purple-600 hover:bg-purple-700 border-purple-600 hover:border-purple-700 text-white" style="width: 10.25rem;">
            <i class="uil uil-sign-in-alt"></i> Log in / Sign up
          </a>
        </li>
        <% end %>
      </ul>
      <!--Login button End-->
      <div id="navigation">
        <!-- Navigation Menu-->
        <ul class="navigation-menu justify-end">

          <li><%= link_to "Home", root_path, class:"sub-menu-item"%></li>
          <li><%= link_to "Jobs", jobs_path, class:"sub-menu-item"%></li>

          <li><a href="contact.html" class="sub-menu-item">Contact</a></li>


      <% if current_user %>

        <li class=" has-submenu parent-menu-item">
          <a href="javascript:void(0)" class="btn btn-icon rounded-full text-white" style="padding-right:0; padding-left:0; border:0">
            <% if current_user.profile_picture.key.present? %>
              <%= cl_image_tag current_user.profile_picture.key, height: 250,width:250, crop: :fill, class:" w-8 rounded-full" %>
            <% else %>
              <%= image_tag("https://res.cloudinary.com/dhufhm6ar/image/upload/v1687785983/Windows_10_Default_Profile_Picture.svg_uajtrb.png", class:"rounded-full") %>
            <% end %>
          </a>
          <ul class="submenu">
            <li><%= link_to "Dashboard", conversations_path, class:"sub-menu-item"%></li>
            <li><%= link_to "Profile", edit_user_registration_path, class:"sub-menu-item"%></li>
            <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"sub-menu-item"%></li>
          </ul>
        </li>
        <% end %>
        </ul>
        <!--end navigation menu-->
      </div>
      <!--end navigation-->
    </div>
    <!--end container-->
  </nav><!--end header-->
  <!-- End Navbar -->